#!/usr/bin/env python3
"""Update public social metrics with layered, best-effort extraction.

Extraction order
----------------
Weibo posts:
1. Public m.weibo.cn JSON endpoint.
2. A real Chromium page, reading network JSON or the visible footer aria-label.

Douyin videos:
1. A real Chromium page, reading network JSON generated by the page itself.
2. Stable ``data-e2e`` attributes / the visible four-number metrics row.

The script never embeds account cookies or private credentials. If a platform asks
for login, CAPTCHA, or device verification, the old value in social-data.json is
retained and a diagnostic file is written. This makes scheduled GitHub Actions
safe: a blocked run cannot overwrite valid values with zero or null.
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
import time
from datetime import date, datetime
from pathlib import Path
from typing import Any, Iterable

try:
    import requests
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Install requests: python -m pip install requests") from exc

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "assets" / "social-data.json"
DEBUG_DIR = ROOT / "debug-social"
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"
)
SESSION = requests.Session()
SESSION.headers.update(
    {
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.7",
        "Accept": "application/json,text/plain,*/*",
    }
)

METRIC_ALIASES = {
    "likes": ("digg_count", "like_count", "attitudes_count", "likes"),
    "comments": ("comment_count", "comments_count", "comments"),
    "favorites": ("collect_count", "favorite_count", "favorites"),
    "shares": ("share_count", "shares"),
    "reposts": ("reposts_count", "repost_count", "reposts"),
}


def log(message: str) -> None:
    print(message, flush=True)


def fetch_json(url: str, **kwargs: Any) -> dict[str, Any] | list[Any] | None:
    try:
        response = SESSION.get(url, timeout=25, **kwargs)
        response.raise_for_status()
        return response.json()
    except Exception as exc:
        log(f"[skip/request] {url}: {exc}")
        return None


def parse_human_number(value: Any) -> int | None:
    """Parse 5469, 1.1万, 12.6w, 3亿 and comma-formatted numbers."""
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value if value >= 0 else None
    if isinstance(value, float):
        return int(value) if math.isfinite(value) and value >= 0 else None

    text = str(value).strip().replace(",", "").replace("＋", "+")
    text = re.sub(r"\s+", "", text)
    if not text or text in {"-", "--", "null", "None"}:
        return None
    match = re.fullmatch(r"([0-9]+(?:\.[0-9]+)?)(万|w|W|亿|k|K|m|M|b|B)?\+?", text)
    if not match:
        return None
    number = float(match.group(1))
    unit = match.group(2)
    multiplier = {
        None: 1,
        "k": 1_000,
        "K": 1_000,
        "w": 10_000,
        "W": 10_000,
        "万": 10_000,
        "亿": 100_000_000,
        "m": 1_000_000,
        "M": 1_000_000,
        "b": 1_000_000_000,
        "B": 1_000_000_000,
    }[unit]
    return int(round(number * multiplier))


def set_number(target: dict[str, Any], key: str, value: Any) -> bool:
    number = parse_human_number(value)
    if number is None or number < 0:
        return False
    if target.get(key) != number:
        target[key] = number
        return True
    return False


def first_number(mapping: dict[str, Any], aliases: Iterable[str]) -> int | None:
    for key in aliases:
        if key in mapping:
            number = parse_human_number(mapping.get(key))
            if number is not None:
                return number
    return None


def recursively_find_stats(node: Any, wanted_id: str | None = None) -> dict[str, int]:
    """Search arbitrary JSON for metrics belonging to the requested item.

    When ``wanted_id`` is supplied, unrelated items are never used as a fallback.
    This avoids a feed/detail response assigning another video's metrics to the
    current card. If the exact item cannot be verified, the caller keeps the
    previous stored values instead of writing potentially incorrect numbers.
    """
    best_unscoped: dict[str, int] = {}
    exact: dict[str, int] = {}

    def metrics_from(mapping: dict[str, Any]) -> dict[str, int]:
        found: dict[str, int] = {}
        for output_key, aliases in METRIC_ALIASES.items():
            number = first_number(mapping, aliases)
            if number is not None:
                found[output_key] = number
        return found

    def walk(value: Any, inside_exact_item: bool = False) -> None:
        nonlocal best_unscoped, exact
        if isinstance(value, dict):
            identifiers = {
                str(value.get(key))
                for key in ("aweme_id", "item_id", "note_id", "id", "mid")
                if value.get(key) is not None
            }
            is_exact_item = inside_exact_item or bool(wanted_id and wanted_id in identifiers)

            candidates: list[dict[str, Any]] = []
            for key in ("statistics", "stats", "stat", "status"):
                child = value.get(key)
                if isinstance(child, dict):
                    candidates.append(child)
            candidates.append(value)

            for candidate in candidates:
                found = metrics_from(candidate)
                if len(found) >= 3:
                    if is_exact_item and len(found) > len(exact):
                        exact = found
                    elif wanted_id is None and len(found) > len(best_unscoped):
                        best_unscoped = found

            for child in value.values():
                walk(child, is_exact_item)
        elif isinstance(value, list):
            for child in value:
                walk(child, inside_exact_item)

    walk(node)
    return exact if wanted_id else best_unscoped


def update_weibo_profile(uid: str, target: dict[str, Any]) -> bool:
    payload = fetch_json(
        "https://m.weibo.cn/api/container/getIndex",
        params={"type": "uid", "value": uid},
        headers={"Referer": f"https://m.weibo.cn/u/{uid}"},
    )
    if not isinstance(payload, dict) or payload.get("ok") != 1:
        return False
    info = payload.get("data", {}).get("userInfo", {})
    return set_number(target, "followers", info.get("followers_count"))


def update_weibo_status_requests(status_id: str, target: dict[str, Any]) -> bool:
    payload = fetch_json(
        "https://m.weibo.cn/statuses/show",
        params={"id": status_id},
        headers={"Referer": f"https://m.weibo.cn/detail/{status_id}"},
    )
    if not isinstance(payload, dict):
        return False
    # Depending on the endpoint version, fields may be top-level or under data.
    source = payload.get("data") if isinstance(payload.get("data"), dict) else payload
    changed = False
    changed |= set_number(target, "likes", source.get("attitudes_count"))
    changed |= set_number(target, "comments", source.get("comments_count"))
    changed |= set_number(target, "reposts", source.get("reposts_count"))
    return changed


def resolve_douyin_item_id(url: str) -> str | None:
    direct = re.search(r"/(?:video|note)/(\d+)", url)
    if direct:
        return direct.group(1)
    try:
        response = SESSION.get(url, timeout=25, allow_redirects=True)
        direct = re.search(r"/(?:video|note)/(\d+)", response.url)
        if direct:
            return direct.group(1)
        direct = re.search(r'"aweme_id"\s*:\s*"?(\d+)"?', response.text)
        return direct.group(1) if direct else None
    except Exception as exc:
        log(f"[skip/resolve] {url}: {exc}")
        return None


def update_douyin_status_legacy(url: str, target: dict[str, Any]) -> bool:
    """Old public endpoint; useful when available, harmless when retired/blocked."""
    item_id = resolve_douyin_item_id(url)
    if not item_id:
        return False
    payload = fetch_json(
        "https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/",
        params={"item_ids": item_id},
        headers={"Referer": "https://www.douyin.com/"},
    )
    stats = recursively_find_stats(payload, item_id) if payload is not None else {}
    changed = False
    for key in ("likes", "comments", "favorites", "shares"):
        if key in stats:
            changed |= set_number(target, key, stats[key])
    return changed


def extract_four_metric_row(texts: Iterable[str]) -> dict[str, int]:
    """Parse a visible Douyin row ordered as like, comment, favorite, share."""
    tokens: list[int] = []
    for text in texts:
        # Keep standalone visible counters, while ignoring timestamps / title prose.
        for token in re.findall(r"(?<!\d)(\d+(?:\.\d+)?(?:万|w|W|亿|k|K)?)(?!\d)", text):
            parsed = parse_human_number(token)
            if parsed is not None:
                tokens.append(parsed)
    # Metrics are shown as exactly four adjacent counters. Choose the last plausible row.
    if len(tokens) >= 4:
        values = tokens[-4:]
        return dict(zip(("likes", "comments", "favorites", "shares"), values))
    return {}


def _safe_filename(text: str) -> str:
    return re.sub(r"[^0-9A-Za-z_.-]+", "_", text)[:90]


def _write_debug(page: Any, label: str, message: str) -> None:
    DEBUG_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    base = DEBUG_DIR / f"{stamp}-{_safe_filename(label)}"
    try:
        page.screenshot(path=str(base.with_suffix(".png")), full_page=True)
    except Exception:
        pass
    try:
        base.with_suffix(".html").write_text(page.content(), encoding="utf-8")
    except Exception:
        pass
    base.with_suffix(".txt").write_text(message, encoding="utf-8")



NUMBER_TOKEN_PATTERN = r"[0-9][0-9,]*(?:\.[0-9]+)?(?:万|亿|[kKmMbB])?\+?"


def extract_labeled_token(text: str, label: str) -> str | None:
    """Return the human-formatted number token next to a visible label."""
    normalized = re.sub(r"\s+", " ", text or "").strip()
    escaped = re.escape(label)
    patterns = (
        rf"({NUMBER_TOKEN_PATTERN})\s*{escaped}",
        rf"{escaped}\s*({NUMBER_TOKEN_PATTERN})",
    )
    for pattern in patterns:
        match = re.search(pattern, normalized, flags=re.IGNORECASE)
        if match:
            return match.group(1)
    return None


def extract_labeled_number(text: str, label: str) -> int | None:
    """Read a human-formatted number immediately before or after a visible label."""
    token = extract_labeled_token(text, label)
    return parse_human_number(token) if token is not None else None


def _read_locator_text(page: Any, selector: str, *, prefer_last: bool = False) -> str:
    locator = page.locator(selector)
    if not locator.count():
        return ""
    node = locator.last if prefer_last else locator.first
    try:
        return node.inner_text(timeout=5_000).strip()
    except Exception:
        return ""


def _read_douyin_profile_metric(
    page: Any,
    selector: str,
    label: str,
) -> tuple[int | None, str]:
    """Read a Douyin profile counter without relying on hashed class names.

    Douyin may render more than one semantic node. Some hidden/early nodes contain
    only the label (for example ``粉丝``), while the visible node contains a sibling
    number. We therefore inspect all matching nodes from last to first, then inspect
    their direct children and nearby parents. This keeps the parser working across
    both known DOM layouts:

    ``<div data-e2e=...><div>粉丝</div><div>22.4万</div></div>``

    and layouts where ``data-e2e`` is attached only to the label element.
    """
    roots = page.locator(selector)
    diagnostic_texts: list[str] = []

    for index in range(roots.count() - 1, -1, -1):
        root = roots.nth(index)
        candidates = [
            root.locator(":scope > div").last,
            root,
            root.locator("xpath=..").first,
            root.locator("xpath=../..").first,
        ]
        for candidate in candidates:
            try:
                if not candidate.count():
                    continue
                raw_text = candidate.inner_text(timeout=5_000).strip()
            except Exception:
                continue
            if not raw_text:
                continue
            if raw_text not in diagnostic_texts:
                diagnostic_texts.append(raw_text)

            # A numeric child such as ``22.4万`` can be parsed directly. A parent
            # such as ``粉丝\n22.4万`` is parsed using the visible label.
            number = parse_human_number(raw_text)
            if number is None:
                number = extract_labeled_number(raw_text, label)
            if number is not None:
                return number, raw_text

    return None, " | ".join(diagnostic_texts)


def browser_collect_profiles(
    data: dict[str, Any],
    *,
    headless: bool = True,
    debug: bool = False,
) -> bool:
    """Collect public account/profile counters from rendered pages.

    This deliberately uses semantic attributes and visible Chinese/English labels
    instead of hashed CSS classes, because the classes change frequently.
    """
    try:
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("[skip/profile/browser] playwright is not installed")
        return False

    sources = data.get("sources", {})
    platforms = data.get("platforms", {})
    any_changed = False

    instagram_handles = {
        "faxuange": "faxuange",
        "hejiashu": "hejiashu1010",
        "jewelrybox": "jewelrybox7231010",
    }

    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(
            headless=headless,
            args=["--no-sandbox"],
        )
        context = browser.new_context(
            user_agent=UA,
            locale="zh-CN",
            viewport={"width": 1365, "height": 900},
            extra_http_headers={"Accept-Language": "zh-CN,zh;q=0.9,en;q=0.7"},
        )

        # Douyin: stable data-e2e anchors supplied by the rendered profile page.
        for name in ("faxuange", "hejiashu"):
            url = sources.get("douyin", {}).get(f"{name}_profile")
            target = platforms.get("douyin", {}).get(name)
            if not url or not isinstance(target, dict):
                continue
            page = context.new_page()
            captured: dict[str, int] = {}
            try:
                page.goto(url, wait_until="domcontentloaded", timeout=60_000)
                page.wait_for_timeout(6_000)

                followers, fans_text = _read_douyin_profile_metric(
                    page,
                    '[data-e2e="user-info-fans"]',
                    "粉丝",
                )
                engagement, likes_text = _read_douyin_profile_metric(
                    page,
                    '[data-e2e="user-info-like"]',
                    "获赞",
                )

                if followers is not None:
                    captured["followers"] = followers
                if engagement is not None:
                    captured["engagement"] = engagement

                changed = False
                for key, value in captured.items():
                    changed |= set_number(target, key, value)
                any_changed |= changed
                log(
                    f"[profile/douyin] {name}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured:
                    _write_debug(
                        page,
                        f"profile-douyin-{name}",
                        f"fans_text={fans_text!r}\nlikes_text={likes_text!r}\n"
                        f"captured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/profile/douyin] timeout {name}: {exc}")
                _write_debug(page, f"profile-douyin-{name}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/profile/douyin] {name}: {exc}")
                _write_debug(page, f"profile-douyin-{name}-error", str(exc))
            finally:
                page.close()

        # Weibo: use the UID-specific fans link and the visible 转评赞 label.
        for name, uid in {
            "faxuange": sources.get("weibo", {}).get("faxuange_uid"),
            "hejiashu": sources.get("weibo", {}).get("hejiashu_uid"),
            "jewelrybox": sources.get("weibo", {}).get("jewelrybox_uid"),
        }.items():
            target = platforms.get("weibo", {}).get(name)
            if not uid or not isinstance(target, dict):
                continue
            page = context.new_page()
            captured: dict[str, int] = {}
            try:
                page.goto(
                    f"https://weibo.com/u/{uid}",
                    wait_until="domcontentloaded",
                    timeout=60_000,
                )
                page.wait_for_timeout(6_000)

                fans_text = _read_locator_text(
                    page,
                    f'a[href*="/u/page/follow/{uid}"][href*="relate=fans"]',
                )
                main_text = _read_locator_text(page, "main") or _read_locator_text(page, "body")
                followers = extract_labeled_number(fans_text, "粉丝")
                engagement = extract_labeled_number(main_text, "转评赞")

                if followers is not None:
                    captured["followers"] = followers
                if engagement is not None:
                    captured["engagement"] = engagement

                changed = False
                for key, value in captured.items():
                    changed |= set_number(target, key, value)
                any_changed |= changed
                log(
                    f"[profile/weibo] {name}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured:
                    _write_debug(
                        page,
                        f"profile-weibo-{name}",
                        f"fans_text={fans_text!r}\n"
                        f"captured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/profile/weibo] timeout {name}: {exc}")
                _write_debug(page, f"profile-weibo-{name}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/profile/weibo] {name}: {exc}")
                _write_debug(page, f"profile-weibo-{name}-error", str(exc))
            finally:
                page.close()

        # Xiaohongshu: read the semantic interaction block and match by labels.
        for name in ("faxuange", "hejiashu", "jewelrybox"):
            url = sources.get("xhs", {}).get(f"{name}_profile")
            target = platforms.get("xhs", {}).get(name)
            if not url or not isinstance(target, dict):
                continue
            page = context.new_page()
            captured: dict[str, int] = {}
            try:
                page.goto(url, wait_until="domcontentloaded", timeout=60_000)
                page.wait_for_timeout(6_000)

                interaction_text = _read_locator_text(page, ".user-interactions")
                if not interaction_text:
                    interaction_text = _read_locator_text(page, ".data-info")
                follower_token = extract_labeled_token(interaction_text, "粉丝")
                engagement_token = extract_labeled_token(interaction_text, "获赞与收藏")
                followers = parse_human_number(follower_token)
                engagement = parse_human_number(engagement_token)

                # Logged-out Xiaohongshu frequently exposes only coarse floors such
                # as ``1万+``. Those are not real-time exact counters and must not
                # overwrite a previously stored, more precise value.
                if followers is not None and follower_token and not follower_token.endswith("+"):
                    captured["followers"] = followers
                if engagement is not None and engagement_token and not engagement_token.endswith("+"):
                    captured["engagement"] = engagement

                changed = False
                for key, value in captured.items():
                    changed |= set_number(target, key, value)
                any_changed |= changed
                log(
                    f"[profile/xhs] {name}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured:
                    _write_debug(
                        page,
                        f"profile-xhs-{name}",
                        f"interaction_text={interaction_text!r}\n"
                        f"captured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/profile/xhs] timeout {name}: {exc}")
                _write_debug(page, f"profile-xhs-{name}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/profile/xhs] {name}: {exc}")
                _write_debug(page, f"profile-xhs-{name}-error", str(exc))
            finally:
                page.close()

        # Instagram: metadata is preferred; visible header text is the fallback.
        for name, handle in instagram_handles.items():
            target = platforms.get("instagram", {}).get(name)
            if not isinstance(target, dict):
                continue
            configured = sources.get("instagram", {}).get(f"{name}_profile")
            url = configured or f"https://www.instagram.com/{handle}/"
            page = context.new_page()
            captured: dict[str, int] = {}
            try:
                page.goto(url, wait_until="domcontentloaded", timeout=60_000)
                page.wait_for_timeout(6_000)

                texts: list[str] = []
                for selector in ('meta[property="og:description"]', 'meta[name="description"]'):
                    locator = page.locator(selector).first
                    if locator.count():
                        value = locator.get_attribute("content")
                        if value:
                            texts.append(value)
                header_text = _read_locator_text(page, "main header")
                if not header_text:
                    header_text = _read_locator_text(page, "header")
                if header_text:
                    texts.append(header_text)
                combined = "\n".join(texts)

                followers = (
                    extract_labeled_number(combined, "粉丝")
                    or extract_labeled_number(combined, "followers")
                    or extract_labeled_number(combined, "follower")
                )
                posts = (
                    extract_labeled_number(combined, "帖子")
                    or extract_labeled_number(combined, "posts")
                    or extract_labeled_number(combined, "post")
                )

                if followers is not None:
                    captured["followers"] = followers
                if posts is not None:
                    captured["posts"] = posts

                changed = False
                for key, value in captured.items():
                    changed |= set_number(target, key, value)
                any_changed |= changed
                log(
                    f"[profile/instagram] {name}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured:
                    _write_debug(
                        page,
                        f"profile-instagram-{name}",
                        f"combined={combined!r}\n"
                        f"captured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/profile/instagram] timeout {name}: {exc}")
                _write_debug(page, f"profile-instagram-{name}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/profile/instagram] {name}: {exc}")
                _write_debug(page, f"profile-instagram-{name}-error", str(exc))
            finally:
                page.close()

        context.close()
        browser.close()

    return any_changed


def browser_collect(
    douyin_jobs: list[tuple[str, dict[str, Any]]],
    weibo_jobs: list[tuple[str, str, dict[str, Any]]],
    *,
    headless: bool = True,
    debug: bool = False,
) -> bool:
    """Use Chromium to collect metrics from page-generated JSON or visible DOM."""
    try:
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("[skip/browser] playwright is not installed")
        return False

    any_changed = False
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(
            headless=headless,
            args=["--no-sandbox"],
        )
        context = browser.new_context(
            user_agent=UA,
            locale="zh-CN",
            viewport={"width": 1365, "height": 900},
            extra_http_headers={"Accept-Language": "zh-CN,zh;q=0.9"},
        )
        for url, target in douyin_jobs:
            item_id = resolve_douyin_item_id(url)
            if not item_id:
                log(f"[skip/browser/douyin] cannot resolve item id: {url}")
                continue
            page = context.new_page()
            captured: dict[str, int] = {}

            def on_response(response: Any) -> None:
                nonlocal captured
                if captured:
                    return
                content_type = (response.headers.get("content-type") or "").lower()
                if "json" not in content_type:
                    return
                lower_url = response.url.lower()
                if not any(word in lower_url for word in ("aweme", "item", "detail", "feed", "note", "post")):
                    return
                try:
                    payload = response.json()
                except Exception:
                    return
                stats = recursively_find_stats(payload, item_id)
                if len(stats) >= 3:
                    captured = stats

            page.on("response", on_response)
            try:
                page_url = url if re.search(r"douyin\.com/(?:video|note)/\d+", url) else f"https://www.douyin.com/video/{item_id}"
                page.goto(
                    page_url,
                    wait_until="domcontentloaded",
                    timeout=60_000,
                )
                page.wait_for_timeout(8_000)
                body_text = page.locator("body").inner_text(timeout=10_000)
                blocked_words = ("验证码", "安全验证", "登录后", "扫码登录", "访问频繁")
                blocked = any(word in body_text for word in blocked_words)

                if not captured:
                    # First try plausible stable data-e2e counters, even when a login
                    # overlay is present: the public metric row often remains in the DOM.
                    selector_map = {
                        "likes": [
                            '[data-e2e="video-digg-count"]',
                            '[data-e2e="video-like-count"]',
                            '[data-e2e="video-digg"]',
                        ],
                        "comments": [
                            '[data-e2e="video-comment-count"]',
                            '[data-e2e="video-comment"]',
                        ],
                        "favorites": [
                            '[data-e2e="video-collect-count"]',
                            '[data-e2e="video-favorite-count"]',
                            '[data-e2e="video-collect"]',
                        ],
                        "shares": [
                            '[data-e2e="video-share-count"]',
                            '[data-e2e="video-share"]',
                        ],
                    }
                    for key, selectors in selector_map.items():
                        for selector in selectors:
                            locator = page.locator(selector).first
                            if locator.count():
                                number = parse_human_number(locator.inner_text().strip())
                                if number is not None:
                                    captured[key] = number
                                    break

                if len(captured) < 3:
                    # Screenshot supplied by the user shows this stable anchor inside
                    # data-e2e="video-detail-info". The surrounding class is hashed,
                    # so we deliberately avoid relying on it.
                    share_anchor = page.locator(
                        '[data-e2e="video-detail-info"] [data-e2e="video-share-icon-container"]'
                    ).first
                    if share_anchor.count():
                        parent = share_anchor.locator("xpath=..").first
                        sibling_texts = parent.locator(":scope > *").all_inner_texts()
                        row = extract_four_metric_row(sibling_texts)
                        if row:
                            captured.update(row)

                if len(captured) < 3 and "/note/" in page_url:
                    # Douyin image-note pages expose the counters through semantic
                    # data-e2e anchors, but the numeric text is stored in DIV elements,
                    # not SPAN elements. Read each counter independently so hashed class
                    # names and layout changes do not matter.
                    try:
                        page.locator('[data-e2e="video-player-digg"]').first.wait_for(
                            state="attached", timeout=15_000
                        )
                    except Exception:
                        pass

                    note_metric_selectors = {
                        "likes": '[data-e2e="video-player-digg"]',
                        "comments": '[data-e2e="feed-comment-icon"]',
                        "favorites": '[data-e2e="video-player-collect"]',
                        "shares": '[data-e2e="video-player-share"]',
                    }

                    for key, selector in note_metric_selectors.items():
                        locator = page.locator(selector).first
                        if not locator.count():
                            continue
                        try:
                            raw_text = locator.inner_text().strip()
                        except Exception:
                            continue

                        # A semantic anchor may contain icon markup plus the visible
                        # number. Extract the final human-readable counter token.
                        tokens = re.findall(
                            r"(?<!\d)(\d+(?:\.\d+)?(?:万|w|W|亿|k|K)?)(?!\d)",
                            raw_text,
                        )
                        for token in reversed(tokens):
                            number = parse_human_number(token)
                            if number is not None:
                                captured[key] = number
                                break

                    # Last fallback: parse the whole interaction rail in display order.
                    if len(captured) < 3:
                        note_panel_selectors = (
                            '[class*="interaction-area"][class*="positionBox"]',
                            '[class*="note-detail-container"] [class*="positionBox"]',
                        )
                        for selector in note_panel_selectors:
                            panel = page.locator(selector).first
                            if not panel.count():
                                continue
                            try:
                                row = extract_four_metric_row([panel.inner_text()])
                                if row:
                                    captured.update(row)
                                    break
                            except Exception:
                                continue

                changed = False
                for key in ("likes", "comments", "favorites", "shares"):
                    if key in captured:
                        changed |= set_number(target, key, captured[key])
                any_changed |= changed
                log(
                    f"[douyin] {item_id}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured or blocked:
                    _write_debug(
                        page,
                        f"douyin-{item_id}",
                        f"blocked={blocked}\ncaptured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/browser/douyin] timeout {item_id}: {exc}")
                _write_debug(page, f"douyin-{item_id}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/browser/douyin] {item_id}: {exc}")
                _write_debug(page, f"douyin-{item_id}-error", str(exc))
            finally:
                page.close()

        for url, status_id, target in weibo_jobs:
            page = context.new_page()
            captured: dict[str, int] = {}

            def on_weibo_response(response: Any) -> None:
                nonlocal captured
                content_type = (response.headers.get("content-type") or "").lower()
                if "json" not in content_type:
                    return
                lower_url = response.url.lower()
                if not any(word in lower_url for word in ("statuses/show", "detail", "ajax/statuses")):
                    return
                try:
                    payload = response.json()
                except Exception:
                    return
                stats = recursively_find_stats(payload, status_id)
                # Weibo's three metrics may sit directly on the status dict.
                if len(stats) >= 2:
                    captured.update(stats)

            page.on("response", on_weibo_response)
            try:
                page.goto(url, wait_until="domcontentloaded", timeout=60_000)
                page.wait_for_timeout(6_000)
                if len(captured) < 2:
                    # The user's DevTools screenshot shows the public footer exposing
                    # "转发,评论,点赞" as an aria-label, e.g. 2902,1234,1.1万.
                    footers = page.locator("footer[aria-label]")
                    for index in range(footers.count()):
                        label = footers.nth(index).get_attribute("aria-label") or ""
                        parts = [part.strip() for part in re.split(r"[,，]", label)]
                        values = [parse_human_number(part) for part in parts]
                        values = [value for value in values if value is not None]
                        if len(values) == 3:
                            captured.update(
                                {"reposts": values[0], "comments": values[1], "likes": values[2]}
                            )
                            break
                changed = False
                for key in ("likes", "comments", "reposts"):
                    if key in captured:
                        changed |= set_number(target, key, captured[key])
                any_changed |= changed
                log(
                    f"[weibo] {status_id}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured:
                    _write_debug(
                        page,
                        f"weibo-{status_id}",
                        f"captured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/browser/weibo] timeout {status_id}: {exc}")
                _write_debug(page, f"weibo-{status_id}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/browser/weibo] {status_id}: {exc}")
                _write_debug(page, f"weibo-{status_id}-error", str(exc))
            finally:
                page.close()

        context.close()
        browser.close()
    return any_changed


def update_douyin_profile(short_url: str, target: dict[str, Any]) -> bool:
    """Best-effort public profile HTML parse; a block simply retains old values."""
    try:
        response = SESSION.get(short_url, timeout=25, allow_redirects=True)
        response.raise_for_status()
        text = response.text
        changed = False
        follower_patterns = (
            r'"follower_count"\s*:\s*(\d+)',
            r'"mplatform_followers_count"\s*:\s*(\d+)',
        )
        # total_favorited is the profile's cumulative received likes.
        like_patterns = (r'"total_favorited"\s*:\s*"?(\d+)"?',)
        for pattern in follower_patterns:
            match = re.search(pattern, text)
            if match:
                changed |= set_number(target, "followers", match.group(1))
                break
        for pattern in like_patterns:
            match = re.search(pattern, text)
            if match:
                changed |= set_number(target, "engagement", match.group(1))
                break
        return changed
    except Exception as exc:
        log(f"[skip/profile/douyin] {short_url}: {exc}")
        return False


def update_xhs_profile(short_url: str, target: dict[str, Any]) -> bool:
    try:
        response = SESSION.get(short_url, timeout=25, allow_redirects=True)
        response.raise_for_status()
        text = response.text
        changed = False
        follower = re.search(r'"fans"\s*:\s*"?(\d+)"?', text)
        interaction = re.search(r'"interaction"\s*:\s*"?(\d+)"?', text)
        if follower:
            changed |= set_number(target, "followers", follower.group(1))
        if interaction:
            changed |= set_number(target, "engagement", interaction.group(1))
        return changed
    except Exception as exc:
        log(f"[skip/profile/xhs] {short_url}: {exc}")
        return False


def recalculate_summary(data: dict[str, Any]) -> bool:
    changed = False
    platforms = data.get("platforms", {})

    # Two artists, three Chinese public platforms, explicitly excluding the duo account.
    follower_total = 0
    complete = True
    for platform in ("douyin", "weibo", "xhs"):
        for name in ("faxuange", "hejiashu"):
            value = platforms.get(platform, {}).get(name, {}).get("followers")
            if not isinstance(value, int):
                complete = False
            else:
                follower_total += value
    if complete:
        changed |= set_number(data.setdefault("summary", {}), "artistFollowers3Platforms", follower_total)

    douyin_engagement = [
        platforms.get("douyin", {}).get(name, {}).get("engagement")
        for name in ("faxuange", "hejiashu")
    ]
    if all(isinstance(value, int) for value in douyin_engagement):
        changed |= set_number(
            data.setdefault("summary", {}),
            "artistDouyinTotalLikes",
            sum(douyin_engagement),
        )

    douyin_items = list(data.get("content", {}).get("douyin", {}).values())
    # The homepage currently describes six representative Douyin posts. Do not
    # replace that six-post total until all six source URLs are configured.
    if len(douyin_items) >= 6 and all(isinstance(item.get("likes"), int) for item in douyin_items):
        changed |= set_number(
            data.setdefault("summary", {}),
            "representativeDouyinLikes",
            sum(item["likes"] for item in douyin_items),
        )
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--headed", action="store_true", help="Show Chromium for local diagnosis")
    parser.add_argument("--debug", action="store_true", help="Always save screenshots and HTML")
    parser.add_argument(
        "--requests-only", action="store_true", help="Skip Playwright browser fallback"
    )
    parser.add_argument(
        "--profiles-only",
        action="store_true",
        help="Update account/profile counters only; skip representative post metrics",
    )
    args = parser.parse_args()

    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    changed = False

    # V0.20 content migration: the third Douyin card now points to a new note.
    # Clear the former post's counters once, then let the normal browser collector
    # repopulate the four metrics from the new public page.
    item03 = data.setdefault("content", {}).setdefault("douyin", {}).setdefault("item03", {})
    new_item03_url = "https://www.douyin.com/note/7670451363546191754"
    if item03.get("url") != new_item03_url:
        item03["url"] = new_item03_url
        item03["label"] = "还能遇见你"
        for metric_key in ("likes", "comments", "favorites", "shares"):
            item03[metric_key] = None
        changed = True
    sources = data.get("sources", {})
    platforms = data.get("platforms", {})

    for name, uid in {
        "faxuange": sources.get("weibo", {}).get("faxuange_uid"),
        "hejiashu": sources.get("weibo", {}).get("hejiashu_uid"),
        "jewelrybox": sources.get("weibo", {}).get("jewelrybox_uid"),
    }.items():
        if uid and name in platforms.get("weibo", {}):
            changed |= update_weibo_profile(str(uid), platforms["weibo"][name])

    for name in ("faxuange", "hejiashu"):
        url = sources.get("douyin", {}).get(f"{name}_profile")
        if url and name in platforms.get("douyin", {}):
            changed |= update_douyin_profile(url, platforms["douyin"][name])

    for name in ("faxuange", "hejiashu", "jewelrybox"):
        url = sources.get("xhs", {}).get(f"{name}_profile")
        if url and name in platforms.get("xhs", {}):
            changed |= update_xhs_profile(url, platforms["xhs"][name])

    if not args.requests_only:
        changed |= browser_collect_profiles(
            data,
            headless=not args.headed,
            debug=args.debug,
        )

    if args.profiles_only:
        data["last_attempt"] = datetime.now().astimezone().isoformat(timespec="seconds")
        if changed:
            data["updated"] = date.today().isoformat()
        DATA_PATH.write_text(
            json.dumps(data, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        log(f"wrote {DATA_PATH}; changed={changed}")
        return 0

    douyin_jobs: list[tuple[str, dict[str, Any]]] = []
    for item in data.get("content", {}).get("douyin", {}).values():
        url = item.get("url")
        if not url:
            continue
        # Cheap legacy endpoint first; browser handles the current signed web APIs.
        changed |= update_douyin_status_legacy(url, item)
        douyin_jobs.append((url, item))

    weibo_jobs: list[tuple[str, str, dict[str, Any]]] = []
    for item in data.get("content", {}).get("weibo", {}).values():
        status_id = str(item.get("status_id") or "")
        url = item.get("url") or item.get("video_url")
        if not status_id or not url:
            continue
        changed |= update_weibo_status_requests(status_id, item)
        weibo_jobs.append((url, status_id, item))

    if not args.requests_only and (douyin_jobs or weibo_jobs):
        changed |= browser_collect(
            douyin_jobs,
            weibo_jobs,
            headless=not args.headed,
            debug=args.debug,
        )

    changed |= recalculate_summary(data)
    data["last_attempt"] = datetime.now().astimezone().isoformat(timespec="seconds")
    if changed:
        data["updated"] = date.today().isoformat()
    DATA_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    log(f"wrote {DATA_PATH}; changed={changed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())