#!/usr/bin/env python3
"""Update public social metrics with layered, best-effort extraction.

Extraction order
----------------
Weibo posts:
1. Public m.weibo.cn JSON endpoint.
2. A real Chromium page, reading network JSON or the visible footer aria-label.

Douyin videos:
1. A real Chromium page, reading network JSON generated by the page itself.
2. Stable ``data-e2e`` attributes / the visible four-number metrics row.

The script never embeds account cookies or private credentials. If a platform asks
for login, CAPTCHA, or device verification, the old value in social-data.json is
retained and a diagnostic file is written. This makes scheduled GitHub Actions
safe: a blocked run cannot overwrite valid values with zero or null.
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
import time
from datetime import date, datetime
from pathlib import Path
from typing import Any, Iterable

try:
    import requests
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Install requests: python -m pip install requests") from exc

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "assets" / "social-data.json"
DEBUG_DIR = ROOT / "debug-social"
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"
)
SESSION = requests.Session()
SESSION.headers.update(
    {
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.7",
        "Accept": "application/json,text/plain,*/*",
    }
)

METRIC_ALIASES = {
    "likes": ("digg_count", "like_count", "attitudes_count", "likes"),
    "comments": ("comment_count", "comments_count", "comments"),
    "favorites": ("collect_count", "favorite_count", "favorites"),
    "shares": ("share_count", "shares"),
    "reposts": ("reposts_count", "repost_count", "reposts"),
}


def log(message: str) -> None:
    print(message, flush=True)


def fetch_json(url: str, **kwargs: Any) -> dict[str, Any] | list[Any] | None:
    try:
        response = SESSION.get(url, timeout=25, **kwargs)
        response.raise_for_status()
        return response.json()
    except Exception as exc:
        log(f"[skip/request] {url}: {exc}")
        return None


def parse_human_number(value: Any) -> int | None:
    """Parse 5469, 1.1万, 12.6w, 3亿 and comma-formatted numbers."""
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value if value >= 0 else None
    if isinstance(value, float):
        return int(value) if math.isfinite(value) and value >= 0 else None

    text = str(value).strip().replace(",", "").replace("＋", "+")
    text = re.sub(r"\s+", "", text)
    if not text or text in {"-", "--", "null", "None"}:
        return None
    match = re.fullmatch(r"([0-9]+(?:\.[0-9]+)?)(万|w|W|亿|k|K)?\+?", text)
    if not match:
        return None
    number = float(match.group(1))
    unit = match.group(2)
    multiplier = {
        None: 1,
        "k": 1_000,
        "K": 1_000,
        "w": 10_000,
        "W": 10_000,
        "万": 10_000,
        "亿": 100_000_000,
    }[unit]
    return int(round(number * multiplier))


def set_number(target: dict[str, Any], key: str, value: Any) -> bool:
    number = parse_human_number(value)
    if number is None or number < 0:
        return False
    if target.get(key) != number:
        target[key] = number
        return True
    return False


def first_number(mapping: dict[str, Any], aliases: Iterable[str]) -> int | None:
    for key in aliases:
        if key in mapping:
            number = parse_human_number(mapping.get(key))
            if number is not None:
                return number
    return None


def recursively_find_stats(node: Any, wanted_id: str | None = None) -> dict[str, int]:
    """Search arbitrary JSON for metrics belonging to the requested item.

    When ``wanted_id`` is supplied, unrelated items are never used as a fallback.
    This avoids a feed/detail response assigning another video's metrics to the
    current card. If the exact item cannot be verified, the caller keeps the
    previous stored values instead of writing potentially incorrect numbers.
    """
    best_unscoped: dict[str, int] = {}
    exact: dict[str, int] = {}

    def metrics_from(mapping: dict[str, Any]) -> dict[str, int]:
        found: dict[str, int] = {}
        for output_key, aliases in METRIC_ALIASES.items():
            number = first_number(mapping, aliases)
            if number is not None:
                found[output_key] = number
        return found

    def walk(value: Any, inside_exact_item: bool = False) -> None:
        nonlocal best_unscoped, exact
        if isinstance(value, dict):
            identifiers = {
                str(value.get(key))
                for key in ("aweme_id", "item_id", "id", "mid")
                if value.get(key) is not None
            }
            is_exact_item = inside_exact_item or bool(wanted_id and wanted_id in identifiers)

            candidates: list[dict[str, Any]] = []
            for key in ("statistics", "stats", "stat", "status"):
                child = value.get(key)
                if isinstance(child, dict):
                    candidates.append(child)
            candidates.append(value)

            for candidate in candidates:
                found = metrics_from(candidate)
                if len(found) >= 3:
                    if is_exact_item and len(found) > len(exact):
                        exact = found
                    elif wanted_id is None and len(found) > len(best_unscoped):
                        best_unscoped = found

            for child in value.values():
                walk(child, is_exact_item)
        elif isinstance(value, list):
            for child in value:
                walk(child, inside_exact_item)

    walk(node)
    return exact if wanted_id else best_unscoped


def update_weibo_profile(uid: str, target: dict[str, Any]) -> bool:
    payload = fetch_json(
        "https://m.weibo.cn/api/container/getIndex",
        params={"type": "uid", "value": uid},
        headers={"Referer": f"https://m.weibo.cn/u/{uid}"},
    )
    if not isinstance(payload, dict) or payload.get("ok") != 1:
        return False
    info = payload.get("data", {}).get("userInfo", {})
    return set_number(target, "followers", info.get("followers_count"))


def update_weibo_status_requests(status_id: str, target: dict[str, Any]) -> bool:
    payload = fetch_json(
        "https://m.weibo.cn/statuses/show",
        params={"id": status_id},
        headers={"Referer": f"https://m.weibo.cn/detail/{status_id}"},
    )
    if not isinstance(payload, dict):
        return False
    # Depending on the endpoint version, fields may be top-level or under data.
    source = payload.get("data") if isinstance(payload.get("data"), dict) else payload
    changed = False
    changed |= set_number(target, "likes", source.get("attitudes_count"))
    changed |= set_number(target, "comments", source.get("comments_count"))
    changed |= set_number(target, "reposts", source.get("reposts_count"))
    return changed


def resolve_douyin_item_id(url: str) -> str | None:
    direct = re.search(r"/(?:video|note)/(\d+)", url)
    if direct:
        return direct.group(1)
    try:
        response = SESSION.get(url, timeout=25, allow_redirects=True)
        direct = re.search(r"/(?:video|note)/(\d+)", response.url)
        if direct:
            return direct.group(1)
        direct = re.search(r'"aweme_id"\s*:\s*"?(\d+)"?', response.text)
        return direct.group(1) if direct else None
    except Exception as exc:
        log(f"[skip/resolve] {url}: {exc}")
        return None


def update_douyin_status_legacy(url: str, target: dict[str, Any]) -> bool:
    """Old public endpoint; useful when available, harmless when retired/blocked."""
    item_id = resolve_douyin_item_id(url)
    if not item_id:
        return False
    payload = fetch_json(
        "https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/",
        params={"item_ids": item_id},
        headers={"Referer": "https://www.douyin.com/"},
    )
    stats = recursively_find_stats(payload, item_id) if payload is not None else {}
    changed = False
    for key in ("likes", "comments", "favorites", "shares"):
        if key in stats:
            changed |= set_number(target, key, stats[key])
    return changed


def extract_four_metric_row(texts: Iterable[str]) -> dict[str, int]:
    """Parse a visible Douyin row ordered as like, comment, favorite, share."""
    tokens: list[int] = []
    for text in texts:
        # Keep standalone visible counters, while ignoring timestamps / title prose.
        for token in re.findall(r"(?<!\d)(\d+(?:\.\d+)?(?:万|w|W|亿|k|K)?)(?!\d)", text):
            parsed = parse_human_number(token)
            if parsed is not None:
                tokens.append(parsed)
    # Metrics are shown as exactly four adjacent counters. Choose the last plausible row.
    if len(tokens) >= 4:
        values = tokens[-4:]
        return dict(zip(("likes", "comments", "favorites", "shares"), values))
    return {}


def _safe_filename(text: str) -> str:
    return re.sub(r"[^0-9A-Za-z_.-]+", "_", text)[:90]


def _write_debug(page: Any, label: str, message: str) -> None:
    DEBUG_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    base = DEBUG_DIR / f"{stamp}-{_safe_filename(label)}"
    try:
        page.screenshot(path=str(base.with_suffix(".png")), full_page=True)
    except Exception:
        pass
    try:
        base.with_suffix(".html").write_text(page.content(), encoding="utf-8")
    except Exception:
        pass
    base.with_suffix(".txt").write_text(message, encoding="utf-8")


def browser_collect(
    douyin_jobs: list[tuple[str, dict[str, Any]]],
    weibo_jobs: list[tuple[str, str, dict[str, Any]]],
    *,
    headless: bool = True,
    debug: bool = False,
) -> bool:
    """Use Chromium to collect metrics from page-generated JSON or visible DOM."""
    try:
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("[skip/browser] playwright is not installed")
        return False

    any_changed = False
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(
            headless=headless,
            args=["--no-sandbox"],
        )
        context = browser.new_context(
            user_agent=UA,
            locale="zh-CN",
            viewport={"width": 1365, "height": 900},
            extra_http_headers={"Accept-Language": "zh-CN,zh;q=0.9"},
        )
        for url, target in douyin_jobs:
            item_id = resolve_douyin_item_id(url)
            if not item_id:
                log(f"[skip/browser/douyin] cannot resolve item id: {url}")
                continue
            page = context.new_page()
            captured: dict[str, int] = {}

            def on_response(response: Any) -> None:
                nonlocal captured
                if captured:
                    return
                content_type = (response.headers.get("content-type") or "").lower()
                if "json" not in content_type:
                    return
                lower_url = response.url.lower()
                if not any(word in lower_url for word in ("aweme", "item", "detail", "feed")):
                    return
                try:
                    payload = response.json()
                except Exception:
                    return
                stats = recursively_find_stats(payload, item_id)
                if len(stats) >= 3:
                    captured = stats

            page.on("response", on_response)
            try:
                page_url = url if re.search(r"douyin\.com/(?:video|note)/\d+", url) else f"https://www.douyin.com/video/{item_id}"
                page.goto(
                    page_url,
                    wait_until="domcontentloaded",
                    timeout=60_000,
                )
                page.wait_for_timeout(8_000)

                # Douyin note / 动图页面的互动栏可能比主体内容更晚渲染。
                if "/note/" in page_url:
                    try:
                        page.locator(
                            'main[data-e2e="note-detail"] [data-e2e="video-player-digg"]'
                        ).first.wait_for(
                            state="attached",
                            timeout=15_000,
                        )
                    except PlaywrightTimeoutError:
                        pass

                body_text = page.locator("body").inner_text(timeout=10_000)
                blocked_words = ("验证码", "安全验证", "登录后", "扫码登录", "访问频繁")
                blocked = any(word in body_text for word in blocked_words)

                if not captured:
                    # First try plausible stable data-e2e counters, even when a login
                    # overlay is present: the public metric row often remains in the DOM.
                    selector_map = {
                        "likes": [
                            # Douyin note / 动图作品页面
                            'main[data-e2e="note-detail"] [data-e2e="video-player-digg"]',

                            # 普通视频页面
                            '[data-e2e="video-digg-count"]',
                            '[data-e2e="video-like-count"]',
                            '[data-e2e="video-digg"]',
                        ],
                        "comments": [
                            # Douyin note / 动图作品页面
                            'main[data-e2e="note-detail"] [data-e2e="feed-comment-icon"]',

                            # 普通视频页面
                            '[data-e2e="video-comment-count"]',
                            '[data-e2e="video-comment"]',
                        ],
                        "favorites": [
                            # Douyin note / 动图作品页面
                            'main[data-e2e="note-detail"] [data-e2e="video-player-collect"]',

                            # 普通视频页面
                            '[data-e2e="video-collect-count"]',
                            '[data-e2e="video-favorite-count"]',
                            '[data-e2e="video-collect"]',
                        ],
                        "shares": [
                            # Douyin note / 动图作品页面
                            'main[data-e2e="note-detail"] [data-e2e="video-player-share"]',

                            # 普通视频页面
                            '[data-e2e="video-share-count"]',
                            '[data-e2e="video-share"]',
                        ],
                    }
                    for key, selectors in selector_map.items():
                        for selector in selectors:
                            locator = page.locator(selector).first
                            if locator.count():
                                number = parse_human_number(locator.inner_text().strip())
                                if number is not None:
                                    captured[key] = number
                                    break

                if len(captured) < 3:
                    # Screenshot supplied by the user shows this stable anchor inside
                    # data-e2e="video-detail-info". The surrounding class is hashed,
                    # so we deliberately avoid relying on it.
                    share_anchor = page.locator(
                        '[data-e2e="video-detail-info"] [data-e2e="video-share-icon-container"]'
                    ).first
                    if share_anchor.count():
                        parent = share_anchor.locator("xpath=..").first
                        sibling_texts = parent.locator(":scope > *").all_inner_texts()
                        row = extract_four_metric_row(sibling_texts)
                        if row:
                            captured.update(row)

                changed = False
                for key in ("likes", "comments", "favorites", "shares"):
                    if key in captured:
                        changed |= set_number(target, key, captured[key])
                any_changed |= changed
                log(
                    f"[douyin] {item_id}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured or blocked:
                    _write_debug(
                        page,
                        f"douyin-{item_id}",
                        f"blocked={blocked}\ncaptured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/browser/douyin] timeout {item_id}: {exc}")
                _write_debug(page, f"douyin-{item_id}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/browser/douyin] {item_id}: {exc}")
                _write_debug(page, f"douyin-{item_id}-error", str(exc))
            finally:
                page.close()

        for url, status_id, target in weibo_jobs:
            page = context.new_page()
            captured: dict[str, int] = {}

            def on_weibo_response(response: Any) -> None:
                nonlocal captured
                content_type = (response.headers.get("content-type") or "").lower()
                if "json" not in content_type:
                    return
                lower_url = response.url.lower()
                if not any(word in lower_url for word in ("statuses/show", "detail", "ajax/statuses")):
                    return
                try:
                    payload = response.json()
                except Exception:
                    return
                stats = recursively_find_stats(payload, status_id)
                # Weibo's three metrics may sit directly on the status dict.
                if len(stats) >= 2:
                    captured.update(stats)

            page.on("response", on_weibo_response)
            try:
                page.goto(url, wait_until="domcontentloaded", timeout=60_000)
                page.wait_for_timeout(6_000)
                if len(captured) < 2:
                    # The user's DevTools screenshot shows the public footer exposing
                    # "转发,评论,点赞" as an aria-label, e.g. 2902,1234,1.1万.
                    footers = page.locator("footer[aria-label]")
                    for index in range(footers.count()):
                        label = footers.nth(index).get_attribute("aria-label") or ""
                        parts = [part.strip() for part in re.split(r"[,，]", label)]
                        values = [parse_human_number(part) for part in parts]
                        values = [value for value in values if value is not None]
                        if len(values) == 3:
                            captured.update(
                                {"reposts": values[0], "comments": values[1], "likes": values[2]}
                            )
                            break
                changed = False
                for key in ("likes", "comments", "reposts"):
                    if key in captured:
                        changed |= set_number(target, key, captured[key])
                any_changed |= changed
                log(
                    f"[weibo] {status_id}: "
                    + (json.dumps(captured, ensure_ascii=False) if captured else "no metrics")
                )
                if debug or not captured:
                    _write_debug(
                        page,
                        f"weibo-{status_id}",
                        f"captured={json.dumps(captured, ensure_ascii=False)}",
                    )
            except PlaywrightTimeoutError as exc:
                log(f"[skip/browser/weibo] timeout {status_id}: {exc}")
                _write_debug(page, f"weibo-{status_id}-timeout", str(exc))
            except Exception as exc:
                log(f"[skip/browser/weibo] {status_id}: {exc}")
                _write_debug(page, f"weibo-{status_id}-error", str(exc))
            finally:
                page.close()

        context.close()
        browser.close()
    return any_changed


def update_douyin_profile(short_url: str, target: dict[str, Any]) -> bool:
    """Best-effort public profile HTML parse; a block simply retains old values."""
    try:
        response = SESSION.get(short_url, timeout=25, allow_redirects=True)
        response.raise_for_status()
        text = response.text
        changed = False
        follower_patterns = (
            r'"follower_count"\s*:\s*(\d+)',
            r'"mplatform_followers_count"\s*:\s*(\d+)',
        )
        # total_favorited is the profile's cumulative received likes.
        like_patterns = (r'"total_favorited"\s*:\s*"?(\d+)"?',)
        for pattern in follower_patterns:
            match = re.search(pattern, text)
            if match:
                changed |= set_number(target, "followers", match.group(1))
                break
        for pattern in like_patterns:
            match = re.search(pattern, text)
            if match:
                changed |= set_number(target, "engagement", match.group(1))
                break
        return changed
    except Exception as exc:
        log(f"[skip/profile/douyin] {short_url}: {exc}")
        return False


def update_xhs_profile(short_url: str, target: dict[str, Any]) -> bool:
    try:
        response = SESSION.get(short_url, timeout=25, allow_redirects=True)
        response.raise_for_status()
        text = response.text
        changed = False
        follower = re.search(r'"fans"\s*:\s*"?(\d+)"?', text)
        interaction = re.search(r'"interaction"\s*:\s*"?(\d+)"?', text)
        if follower:
            changed |= set_number(target, "followers", follower.group(1))
        if interaction:
            changed |= set_number(target, "engagement", interaction.group(1))
        return changed
    except Exception as exc:
        log(f"[skip/profile/xhs] {short_url}: {exc}")
        return False


def recalculate_summary(data: dict[str, Any]) -> bool:
    changed = False
    platforms = data.get("platforms", {})

    # Two artists, three Chinese public platforms, explicitly excluding the duo account.
    follower_total = 0
    complete = True
    for platform in ("douyin", "weibo", "xhs"):
        for name in ("faxuange", "hejiashu"):
            value = platforms.get(platform, {}).get(name, {}).get("followers")
            if not isinstance(value, int):
                complete = False
            else:
                follower_total += value
    if complete:
        changed |= set_number(data.setdefault("summary", {}), "artistFollowers3Platforms", follower_total)

    douyin_engagement = [
        platforms.get("douyin", {}).get(name, {}).get("engagement")
        for name in ("faxuange", "hejiashu")
    ]
    if all(isinstance(value, int) for value in douyin_engagement):
        changed |= set_number(
            data.setdefault("summary", {}),
            "artistDouyinTotalLikes",
            sum(douyin_engagement),
        )

    douyin_items = list(data.get("content", {}).get("douyin", {}).values())
    # The homepage currently describes six representative Douyin posts. Do not
    # replace that six-post total until all six source URLs are configured.
    if len(douyin_items) >= 6 and all(isinstance(item.get("likes"), int) for item in douyin_items):
        changed |= set_number(
            data.setdefault("summary", {}),
            "representativeDouyinLikes",
            sum(item["likes"] for item in douyin_items),
        )
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--headed", action="store_true", help="Show Chromium for local diagnosis")
    parser.add_argument("--debug", action="store_true", help="Always save screenshots and HTML")
    parser.add_argument(
        "--requests-only", action="store_true", help="Skip Playwright browser fallback"
    )
    args = parser.parse_args()

    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    changed = False

    # V0.20 content migration: the third Douyin card now points to a new note.
    # Clear the former post's counters once, then let the normal browser collector
    # repopulate the four metrics from the new public page.
    item03 = data.setdefault("content", {}).setdefault("douyin", {}).setdefault("item03", {})
    new_item03_url = "https://www.douyin.com/note/7670451363546191754"
    if item03.get("url") != new_item03_url:
        item03["url"] = new_item03_url
        item03["label"] = "还能遇见你"
        for metric_key in ("likes", "comments", "favorites", "shares"):
            item03[metric_key] = None
        changed = True
    sources = data.get("sources", {})
    platforms = data.get("platforms", {})

    for name, uid in {
        "faxuange": sources.get("weibo", {}).get("faxuange_uid"),
        "hejiashu": sources.get("weibo", {}).get("hejiashu_uid"),
        "jewelrybox": sources.get("weibo", {}).get("jewelrybox_uid"),
    }.items():
        if uid and name in platforms.get("weibo", {}):
            changed |= update_weibo_profile(str(uid), platforms["weibo"][name])

    for name in ("faxuange", "hejiashu"):
        url = sources.get("douyin", {}).get(f"{name}_profile")
        if url and name in platforms.get("douyin", {}):
            changed |= update_douyin_profile(url, platforms["douyin"][name])

    for name in ("faxuange", "hejiashu", "jewelrybox"):
        url = sources.get("xhs", {}).get(f"{name}_profile")
        if url and name in platforms.get("xhs", {}):
            changed |= update_xhs_profile(url, platforms["xhs"][name])

    douyin_jobs: list[tuple[str, dict[str, Any]]] = []
    for item in data.get("content", {}).get("douyin", {}).values():
        url = item.get("url")
        if not url:
            continue
        # Cheap legacy endpoint first; browser handles the current signed web APIs.
        changed |= update_douyin_status_legacy(url, item)
        douyin_jobs.append((url, item))

    weibo_jobs: list[tuple[str, str, dict[str, Any]]] = []
    for item in data.get("content", {}).get("weibo", {}).values():
        status_id = str(item.get("status_id") or "")
        url = item.get("url") or item.get("video_url")
        if not status_id or not url:
            continue
        changed |= update_weibo_status_requests(status_id, item)
        weibo_jobs.append((url, status_id, item))

    if not args.requests_only and (douyin_jobs or weibo_jobs):
        changed |= browser_collect(
            douyin_jobs,
            weibo_jobs,
            headless=not args.headed,
            debug=args.debug,
        )

    changed |= recalculate_summary(data)
    data["last_attempt"] = datetime.now().astimezone().isoformat(timespec="seconds")
    if changed:
        data["updated"] = date.today().isoformat()
    DATA_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    log(f"wrote {DATA_PATH}; changed={changed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
